### ISSUE TITLE
アコーディオンメニューが個別に開かない件（テスト投稿）

### ISSUE THREAD

**Issue by rusian0** [Tatami-Server/tatamiserver.github.io#1]
@alexandraerina 

```javascript
 <Subtitle subtitle="よくある質問"/>
       <div className={HelperStyle["Question-wrapper"]}>
         {QuestionList.map(({question, answer}) =>
           <QuestionAccordion
             key={question.answer}
             question={question}
             answer={answer}
           />
         )}
  </div>
```

- jofawije
- test

> また、今回色々調べてみて僕も気付かされたんですが、QuestionListのようなオブジェクトを含んだ配列をstateで管理するのはやめたほうがよさそうであることと、そもそも今回のAccordionのようにパーツとしてはっきりしてるものはコンポーネント化すべきなのかなと。

![image](https://user-images.githubusercontent.com/33826764/204583554-cbd62b2c-2821-47d9-92e0-30df7eadb72d.png)

そのファイルでしか使わないものもコンポーネント化するべきなのですか、
今ファイルをpageとcomponentに分けているのですが、基本pageのファイルにはあまり書かずに、componentをimportしてきて見た目を作るという認識でよいですか？

**Comment by alexandraerina** [comment]
aaa
